# mkconda requires a current GIT_TOKEN on TravisCI kutaslab/mkconda
env:
    - PACKAGE_NAME: mkconda   # for the conda_upload.sh deploy script
language: minimal
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    # override conda defaults https://github.com/conda/conda/issues/7038
    # priority is last in, goes to the top
    - conda info -a
    # - conda config --prepend channels kutaslab
    # - conda config --append channels conda-forge
    # - conda config --add default_channels conda-forge
    # - conda config --add default_channels defaults
    # - conda config --add default_channels kutaslab
    #- conda info 
install:
    - conda install -q conda-build conda-verify
    - conda clean --all
    - conda build -c kutaslab -c defaults -c conda-forge conda
    - conda create --name mkconda_env
    - conda activate mkconda_env
    - conda install --name mkconda_env -c local mkconda # -c kutaslab -c defaults -c conda-forge
    - conda list
    - lscpu
    - python -c 'import numpy; numpy.show_config()'
    - python -c "import mkpy; print(mkpy.__version__)"
    - python -c "import fitgrid; print(fitgrid.__version__)"
# script:
# after_success:
before_deploy:
    - conda install anaconda-client
    - conda list
deploy:
    - provider: script
      skip_cleanup: true
      script: bash ./ci/conda_upload.sh
      on:
        all_branches: true
