package:
  name: mkconda
  version: "0.1.0.dev0"

build:
  noarch: python

requirements:
  run:
    - blas=*=*mkl
    - fitgrid
    - spudtr
    - mkpy
    - jupyterlab
    - numba
    - spyder
    - rapids
    - cudatoolkit-dev
    - pytorch
    - r-tidyverse
    - r-irkernel
    - firefox

test:
  imports:
    - mkpy
    - spudtr
    - fitgrid
